### ISSUE TITLE
Instructions for inference are incorrect

### ISSUE THREAD

**Issue by mantyni** [yasinalm/gramme#6]
Thanks for sharing the code. I am trying to run an inference test for odometry trajectory using test_mono.py script with a pretrained Radiate dataset. However, instructions provided in the readme file are not correct. 

Firstly, test_mono.py should specify in the arguments --pretrained-pose and not --pretrained-disp (currently in the readme): 
python test_mono.py /path/to/dataset/ --dataset dataset_name **--pretrained-disp** /path/to/pretrained_model --results-dir /path/to/save/results # for monocular odometry
 
Secondly, I get the following error trying to run the script. I guess sequence parameter is missing however, it is not clear from description what sequence is and what it should contain: 
python3 test_mono.py ./datasets/radiate_city_1/ --dataset radiate --pretrained-pose mono_posenet_checkpoint.pth.tar-20221020T225942Z-001/mono_posenet_checkpoint.pth.tar --results-dir ./results
=> creating model
=> using pre-trained weights for PoseResNet
Traceback (most recent call last):
  File "test_mono.py", line 260, in <module>
    main()
  File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test_mono.py", line 128, in main
    raise argparse.ArgumentError(
TypeError: __init__() missing 1 required positional argument: 'message'

Please can you update the instructions and specify correct arguments for running the inference tests.

**Comment by QingTianNNN** [comment]
Hello, do you know how to get train.txt and val.txt? I would be grateful if you could answer it
